version: '3'
services:
  server:
    build:
      context: ./
    container_name: bsd_server
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
    volumes:
      - ./:/app
      - ../client:/client
    ports:
      - 80:5000
    